# zf250518.1737

#version: "3.7"
services:
  # mqtt5 eclipse-mosquitto
  mqtt-2:
    image: eclipse-mosquitto
    container_name: mqtt-2
    ports:
      - "18884:1883" #default mqtt port
      - "19002:9001" #default mqtt port for websockets
    volumes:
      - ./config:/mosquitto/config:rw
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
    restart: unless-stopped

# volumes for mapping data,config and log
volumes:
  config:
  data:
  log:

networks:
  default:
    name: mqtt-2-network
