# zf250518.1547

#version: "3.7"
services:
  # mqtt5 eclipse-mosquitto
  mqtt-1:
    image: eclipse-mosquitto
    container_name: mqtt-1
    ports:
      - "18883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./config:/mosquitto/config:rw
      - ./data:/mosquitto/data:rw
      - ./log:/mosquitto/log:rw
    restart: unless-stopped

# volumes for mapping data,config and log
volumes:
  config:
  data:
  log:

networks:
  default:
    name: mqtt-1-network
